### PR TITLE
Simplifying repo

### PR DESCRIPTION
**Pull request by sabeegrewal**
In this PR, we reduce the scope of this repo to simply enumerate the existing ecosystem and provide links to get there.

### CODE REVIEW

**Comment by jackbond** [comment]
@sabeegrewal Why have you guys gutted this Github resource? Is this a direction that all azure projects like CosmosDB and others intend to do?

**Comment by sabeegrewal** [comment]
Hey @jackbond, we talked about it and this didn't seem like a good place for anything besides encapsulating our open-source ecosystem and providing samples. Issues were being opened and not being tracked which I really hate to see. For any type of issue, there is a better channel to report it than this one:

* Documentation issues/feedback -> File an issue here https://github.com/MicrosoftDocs/azure-docs
* Library issues/feedback -> File an issue in the respective repo
* Service-side issues -> Open a support ticket on Azure (which comes straight to our team!)
* Service-side feedback/requests -> I'm in the process of getting something like [this](https://feedback.azure.com/forums/216926-service-bus) setup for Event Hubs 

Once we have the feedback forum setup, adding the correct support/feedback channels to the README on this repo may be a good idea. 

Now, with all that said, our goal was **not** to make this repo seem "gutted". Is there anything that you feel is missing now that you appreciated? Is there anything else you think this repo should provide? We'd love feedback on this and we're willing to implement good ideas as they come in 👍  

Thank you for taking the time! 

P.S. This is not an Azure-wide initiative - this is just us (the Event Hubs team) trying to make sure we have a good process in place!

**Comment by jackbond** [comment]
@sabeegrewal Ok, so the other EventHub GitHubs like https://github.com/azure/azure-event-hubs-dotnet will remain unchanged?

**Comment by sabeegrewal** [comment]
Yes! Users that use our open-source stuff should be able to get support *fast* via GitHub - that's the goal we're seriously pushing for. We're happy to (and want to) support our GitHub projects on GitHub :)

**Pull request merged**
