### PR TITLE
Add pointers to new packages in readme files at the root and for .Net legacy package

### PR DESCRIPTION
**Pull request by ramya-rao-a**
This PR has the below changes

- Updated the root readme file to have pointers to the new packages and their samples
- Add missing readme file for the folder with samples for the older WindowsAzure.ServiceBus package
- Update readme for the sample on RBAC for the older WindowsAzure.ServiceBus package to pointer to the corresponding sample in the new package

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
cc @spelluru, @serkantkaraca, @lilyjma

**Review by spelluru — APPROVED** [review]
Look good from my side. Thanks.

**Review by JamesBirdsall — APPROVED** [review]
Looks good.

**Comment by ramya-rao-a** [comment]
Thanks for the review and approval @JamesBirdsall 

I don't have permissions to merge the PR, can you please help with that?

**Pull request merged**
