### PR TITLE
C#/.NetCore EventHubClient and EventProcessorHost

### PR DESCRIPTION
**Pull request by dstuckims**

### CODE REVIEW

**Comment by hmlam** [comment]
How come I am seeing Java related check-ins in this PR? are those just piggy back for this PR or we are missing a git pull?

**Comment by dstuckims** [comment]
It was probably me trying to keep it close to up to date with the master branch.   I didn't make any java updates personally,  probably got them through pulling master.

**Comment by hmlam** [comment]
@SreeramGarlapati  should take a look and make sure all the changes in this PR is ok to be in master... just in case.

**Comment by dstuckims** [comment]
If there's something I can do in GIT to make this better please let me know.  Should I pull Azure/master, and try to rebase all this work on that???

**Comment by dstuckims** [comment]
I'm pulling master into develop in an upcoming pull request, then I'll submit a pull request to put the .NET Core 1.0 RTM changes on top of that.

**Pull request closed without merging**
